### ISSUE TITLE
data.yaml format changes or is incorrect.

### ISSUE THREAD

**Issue by maxxam95** [Jaykumaran/Robotic_Arm_Keypoint_Tracking_YoloV8-Pose#1]
Hi there,

First of all, I want to express my gratitude for the awesome tutorial. It has been incredibly helpful.

I noticed a small issue with the data.yaml file format. In the tutorial, it suggests using the following format:
```
names:
0: joints
```
However, I found that this format doesn't work for me. Instead, the correct format that works is:
```
names:
- joints
```
I thought it would be helpful to bring this to your attention.
Thanks again for the great tutorial!

Best regards,
Max

**Comment by Jaykumaran** [comment]
> Hi there,
> 
> First of all, I want to express my gratitude for the awesome tutorial. It has been incredibly helpful.
> 
> I noticed a small issue with the data.yaml file format. In the tutorial, it suggests using the following format:
> 
> ```
> names:
> 0: joints
> ```
> 
> However, I found that this format doesn't work for me. Instead, the correct format that works is:
> 
> ```
> names:
> - joints
> ```
> 
> I thought it would be helpful to bring this to your attention. Thanks again for the great tutorial!
> 
> Best regards, Max

**Comment by Jaykumaran** [comment]
This should but it has to be like 

```
names:
    0: joints
```
  
 I ve used number/index as if multiple classes were there means we can augment

```
names:
     0: joints
     1: skeleton
     2: face_keypoints
```
  
 For proper mapping of classes used while annoattaion and assigning the,m while training is important in multi class.
